/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.sp.petaltech.vendas.view;

import br.sp.petaltech.produtos.Produtos;
import br.sp.petaltech.vendas.dao.VendaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class LancamentosView extends javax.swing.JFrame {

    public static Produtos produto;

    public LancamentosView(Produtos obj) {
        initComponents();
    }

    /**
     * Creates new form LancamentosView
     */
    public LancamentosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaLançamentos = new javax.swing.JPanel();
        Produto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        txtProduto = new javax.swing.JTextField();
        Lançamentos = new javax.swing.JPanel();
        lblItem1 = new javax.swing.JLabel();
        lblItens = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        spnQTD1 = new javax.swing.JSpinner();
        lblItens1 = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblProduto = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnAtualizarValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Produto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Valor", "Descrição", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdutoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout ProdutoLayout = new javax.swing.GroupLayout(Produto);
        Produto.setLayout(ProdutoLayout);
        ProdutoLayout.setHorizontalGroup(
            ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(txtProduto))
                .addGap(24, 24, 24))
        );
        ProdutoLayout.setVerticalGroup(
            ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        Lançamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lançamentos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem1.setText("1.");
        lblItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblItem1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblItens.setBackground(new java.awt.Color(204, 204, 204));
        lblItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItens.setText("Item");
        lblItens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQuantidade.setBackground(new java.awt.Color(204, 204, 204));
        lblQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantidade.setText("Quantidade");
        lblQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        spnQTD1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));

        lblItens1.setBackground(new java.awt.Color(204, 204, 204));
        lblItens1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItens1.setText("Produto");
        lblItens1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDescricao.setBackground(new java.awt.Color(204, 204, 204));
        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescricao.setText("Valor Total");
        lblDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAtualizarValor.setText("Atulizar");
        btnAtualizarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LançamentosLayout = new javax.swing.GroupLayout(Lançamentos);
        Lançamentos.setLayout(LançamentosLayout);
        LançamentosLayout.setHorizontalGroup(
            LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LançamentosLayout.createSequentialGroup()
                .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LançamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(lblItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblItens1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(spnQTD1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LançamentosLayout.createSequentialGroup()
                                .addComponent(btnAtualizarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LançamentosLayout.createSequentialGroup()
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LançamentosLayout.setVerticalGroup(
            LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LançamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItens1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblItens)
                        .addComponent(lblQuantidade)
                        .addComponent(lblDescricao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAtualizarValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnQTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTelaLançamentosLayout = new javax.swing.GroupLayout(pnlTelaLançamentos);
        pnlTelaLançamentos.setLayout(pnlTelaLançamentosLayout);
        pnlTelaLançamentosLayout.setHorizontalGroup(
            pnlTelaLançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaLançamentosLayout.createSequentialGroup()
                .addGroup(pnlTelaLançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lançamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTelaLançamentosLayout.setVerticalGroup(
            pnlTelaLançamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaLançamentosLayout.createSequentialGroup()
                .addComponent(Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lançamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaLançamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaLançamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        VendaDAO venda = new VendaDAO();
        int linhaSelecionada = tblProduto.getSelectedRow();
        ArrayList<Produtos> lista = new ArrayList<Produtos>();

        //Passa o produto da tabela para variáveis
        int ID = Integer.parseInt(tblProduto.getValueAt(linhaSelecionada, 0).toString());
        String nome = tblProduto.getValueAt(linhaSelecionada, 1).toString();
        double valor = Double.parseDouble(tblProduto.getValueAt(linhaSelecionada, 2).toString());
        String descricao = tblProduto.getValueAt(linhaSelecionada, 3).toString();
        double estoque = Double.parseDouble(tblProduto.getValueAt(linhaSelecionada, 4).toString());
        int quantidade = Integer.parseInt(spnQTD1.getValue().toString());
        double novoEstoque = estoque - Double.parseDouble(spnQTD1.getValue().toString());

        //Passa os atributos para o objeto
        Produtos produto = new Produtos(ID, nome, valor, descricao, quantidade);

        boolean retorno = venda.retirarEstoque(estoque, ID);
        
        lista.add(produto);

        DefaultTableModel modelo = (DefaultTableModel) TelaVendas.tblCarrinho.getModel();

        modelo.setRowCount(0);

        for (Produtos produtoLista : lista) {

            modelo.addRow(new String[]{String.valueOf(produtoLista.getCod()),
                produtoLista.getNome(),
                produtoLista.getDesc(),
                String.valueOf(quantidade),
                String.valueOf(produtoLista.getPc()),
                String.valueOf(quantidade*produtoLista.getPc())
            });

            if (linhaSelecionada == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um produto!");
            } else if (Integer.parseInt(spnQTD1.getValue().toString()) == 0 && novoEstoque > 0) {
                JOptionPane.showMessageDialog(this, "Insira uma quatidade válida!");
            } else if (Integer.parseInt(spnQTD1.getValue().toString()) == 0 && novoEstoque == 0) {
                JOptionPane.showMessageDialog(this, "Estoque esgotado!\nSelecione outro produto");
            } else if (retorno) {
                JOptionPane.showMessageDialog(this, "Lançamento Concluído");
            }
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void txtProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyReleased
        VendaDAO venda = new VendaDAO();
        ArrayList<Produtos> lista = venda.filtrarPorNomeProduto(txtProduto.getText());

        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        modelo.setRowCount(0);

        for (Produtos produto : lista) {

            modelo.addRow(new String[]{String.valueOf(produto.getCod()),
                produto.getNome(),
                String.valueOf(produto.getPc()),
                produto.getDesc(),
                String.valueOf(produto.getQtdEstoque())
            });

        }
    }//GEN-LAST:event_txtProdutoKeyReleased

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        lblProduto.setText(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 1).toString());
        int linhaSelecionada = tblProduto.getSelectedRow();
        Double estoque = Double.parseDouble(tblProduto.getModel().getValueAt(linhaSelecionada, 4).toString());

        int limite = estoque.intValue();
        SpinnerNumberModel sm = new SpinnerNumberModel(1, 0, limite, 1);

        spnQTD1.setModel(sm);

        lblValorTotal.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void btnAtualizarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarValorActionPerformed
        Double valorProduto = Double.parseDouble(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2).toString());
        Double quantidade = Double.parseDouble(spnQTD1.getValue().toString());

        Double novoValor = valorProduto * quantidade;

        lblValorTotal.setText(novoValor.toString());
    }//GEN-LAST:event_btnAtualizarValorActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancamentosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lançamentos;
    private javax.swing.JPanel Produto;
    private javax.swing.JButton btnAtualizarValor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblItens;
    private javax.swing.JLabel lblItens1;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlTelaLançamentos;
    private javax.swing.JSpinner spnQTD1;
    private static javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
